[package]
name = "wikdict"
version = "0.1.1"
edition = "2021"

description = "Rust library for downloading and querying WikDict SQLite dictionaries"

license = "MIT OR Apache-2.0"

repository = "https://github.com/YOUR_USERNAME/wikdict-rs"

readme = "README.md"

keywords = [
    "wikdict",
    "dictionary",
    "translation",
    "sqlite",
]

categories = [
    "localization",
    "database",
]

[dependencies]
futures-util = "0.3"
reqwest = {
    version = "0.13",
    default-features = false,
    features = ["rustls-tls", "stream"]
}
rusqlite = {
    version = "0.40",
    features = ["bundled"]
}
serde = {
    version = "1",
    features = ["derive"]
}
thiserror = "2.0.20"
tokio = {
    version = "1.53",
    features = ["fs", "io-util"]
}
